export const skips = [
    'mild',
    'shade',
    'acid',
    'fireball',
    'tunnel',
    'dark',
    'spicy',
] as const;

export const pools = [
    'dreamer',
    'skill',
    'charm',
    'key',
    'mask_shard',
    'vessel_fragment',
    'pale_ore',
    'charm_notch',
    'geo_chest',
    'relic',
    'rancid_egg',
    'stag',
    'map',
    'whisper_root',
    'grub',
    'lifeblood_cocoon',
    'soul_totem',
    'lore_tablet',
    'grimmkin_flame',
    'geo_rock',
    'boss_essence',
    'boss_geo',
    'journal',
    'junk_pit',
    'palace',
] as const;

export const modes = [
    'item',
    'area',
    'room',
] as const;

export const miscs = [
    'random_focus',
    'random_swim',
    'elevator_pass',
    'cursed_nail',
    'cursed_notch',
    'cursed_mask',
    'split_cloak',
    'split_claw',
    'egg_shop',
    'mimic',
    'random_charm_cost',
    'duplicate_major',
    'curse',
] as const;

export type Skip = typeof skips[number];
export type Pool = typeof pools[number];
export type Mode = typeof modes[number];
export type Misc = typeof miscs[number];

export const skipsPreset: Record<string, Skip[]> = {
    easy:   [],
    medium: [
        'mild',
        'shade',
    ],
    hard: [
        'mild',
        'shade',
        'acid',
        'fireball',
        'tunnel',
        'dark',
        'spicy',
    ],
};

export const poolPreset: Record<string, Pool[]> = {
    standard: [
        'dreamer',
        'skill',
        'charm',
        'key',
        'geo_chest',
        'mask_shard',
        'vessel_fragment',
        'pale_ore',
        'charm_notch',
        'rancid_egg',
        'relic',
        'stag',
    ],
    super: [
        'dreamer',
        'skill',
        'charm',
        'key',
        'geo_chest',
        'mask_shard',
        'vessel_fragment',
        'pale_ore',
        'charm_notch',
        'rancid_egg',
        'relic',
        'map',
        'stag',
        'grub',
        'whisper_root',
    ],
    lifetotems: [
        'dreamer',
        'skill',
        'charm',
        'key',
        'geo_chest',
        'mask_shard',
        'vessel_fragment',
        'pale_ore',
        'charm_notch',
        'rancid_egg',
        'relic',
        'stag',
        'lifeblood_cocoon',
        'soul_totem',
        'palace',
        'boss_geo',
    ],
    spoiler_dab: [
        'dreamer',
        'skill',
        'charm',
        'key',
        'geo_chest',
        'mask_shard',
        'vessel_fragment',
        'pale_ore',
        'charm_notch',
        'rancid_egg',
        'relic',
        'map',
        'stag',
        'whisper_root',
        'lifeblood_cocoon',
        'soul_totem',
    ],
    everything: [
        'dreamer',
        'skill',
        'charm',
        'key',
        'geo_chest',
        'mask_shard',
        'vessel_fragment',
        'pale_ore',
        'charm_notch',
        'rancid_egg',
        'relic',
        'map',
        'stag',
        'grub',
        'whisper_root',
        'geo_rock',
        'lifeblood_cocoon',
        'soul_totem',
        'palace',
        'lore_tablet',
        'grimmkin_flame',
        'boss_essence',
        'boss_geo',
        'journal',
        'junk_pit',
    ],
};
