export const versions = ['3.13', '4.0'];

export const skips313 = ['mild', 'shade', 'acid', 'fireball', 'tunnel', 'dark', 'spicy'];

export const skipsPreset313 = {
    easy:   [],
    medium: ['mild', 'shade'],
    hard:   ['mild', 'shade', 'acid', 'fireball', 'tunnel', 'dark', 'spicy'],
};

export const items313 = ['dreamer', 'skill', 'charm', 'key', 'mask_shard', 'vessel_fragment', 'pale_ore', 'charm_notch', 'geo_chest', 'relic', 'rancid_egg', 'stag', 'map', 'whisper_root', 'grub', 'lifeblood_cocoon', 'soul_totem', 'lore_tablet', 'grimmkin_flame', 'geo_rock', 'boss_essence', 'boss_geo', 'journal', 'junk_pit', 'palace', 'egg_shop', 'mimic'];

export const itemsPreset313 = {
    standard: [
        'dreamer',
        'skill',
        'charm',
        'key',
        'geo_chest',
        'mask_shard',
        'vessel_fragment',
        'pale_ore',
        'charm_notch',
        'rancid_egg',
        'relic',
        'stag',
    ],

    super: [
        'dreamer',
        'skill',
        'charm',
        'key',
        'geo_chest',
        'mask_shard',
        'vessel_fragment',
        'pale_ore',
        'charm_notch',
        'rancid_egg',
        'relic',
        'map',
        'stag',
        'grub',
        'whisper_root'],

    lifetotems: [
        'dreamer',
        'skill',
        'charm',
        'key',
        'geo_chest',
        'mask_shard',
        'vessel_fragment',
        'pale_ore',
        'charm_notch',
        'rancid_egg',
        'relic',
        'stag',
        'lifeblood_cocoon',
        'soul_totem',
        'palace',
        'boss_geo',
    ],

    spoiler_dab: [
        'dreamer',
        'skill',
        'charm',
        'key',
        'geo_chest',
        'mask_shard',
        'vessel_fragment',
        'pale_ore',
        'charm_notch',
        'rancid_egg',
        'relic',
        'map',
        'stag',
        'whisper_root',
        'lifeblood_cocoon',
        'soul_totem',
    ],

    everything: [
        'dreamer',
        'skill',
        'charm',
        'key',
        'geo_chest',
        'mask_shard',
        'vessel_fragment',
        'pale_ore',
        'charm_notch',
        'rancid_egg',
        'relic',
        'map',
        'stag',
        'grub',
        'whisper_root',
        'geo_rock',
        'lifeblood_cocoon',
        'soul_totem',
        'palace',
        'lore_tablet',
        'grimmkin_flame',
        'boss_essence',
        'boss_geo',
        'journal',
        'junk_pit',
    ],
};
