export const skips = [
    'precise_movement',
    'proficient_combat',
    'background_pogo',
    'enemy_pogo',
    'obscure',
    'shade',
    'infection',
    'fireball',
    'acid',
    'spike_tunnel',
    'dark_room',
    'damage_boost',
    'dangerous',
    'complex',
    'difficult',
] as const;

export const pools = [
    'dreamer',
    'skill',
    'charm',
    'key',
    'mask_shard',
    'vessel_fragment',
    'pale_ore',
    'charm_notch',
    'geo_chest',
    'relic',
    'rancid_egg',
    'stag',
    'map',
    'whispering_root',
    'grub',
    'lifeblood_cocoon',
    'soul_totem',
    'lore_tablet',
    'grimmkin_flame',
    'geo_rock',
    'boss_essence',
    'boss_geo',
    'journal',
    'junk_pit',
] as const;
